language: go

os:
    - linux
    - osx

go:
    - 1.9.x
    - 1.8.x
    - 1.7.x
    - 1.6.x

script:
    - mkdir -p ${GOPATH}/src/github.com/CodisLabs/codis
    - cp -a pkg ${GOPATH}/src/github.com/CodisLabs/codis
    - make codis-dashboard
    - make gotest

before_deploy:
    - export   DEPLOY_TARGET=codis${TRAVIS_TAG}-go${TRAVIS_GO_VERSION}-${TRAVIS_OS_NAME}
    - mv bin ${DEPLOY_TARGET}
    - zip -r ${DEPLOY_TARGET}.zip ${DEPLOY_TARGET} && tar -czvf ${DEPLOY_TARGET}.tar.gz ${DEPLOY_TARGET}

deploy:
    provider: releases
    overwrite: true
    api_key:
        secure: RKVkoCwNJej19d6KbgpxkwJ9H3bu0icS895G9BkaytUjRVO129S93L4xpHRfeIyySZNVrd4P/le01JIJ6/Fl89wKCc/5oX07aFo6l0w/+JKxSn33FsGh8pGTg5wt9Vm5aqccB6lbkylwKrvDUOwuJCbzMva8f1YrWv0a+3I6JKU=
    file:
        - ${DEPLOY_TARGET}.zip
        - ${DEPLOY_TARGET}.tar.gz
    skip_cleanup: true
    on:
        repo: CodisLabs/codis
        tags: true
        condition: $TRAVIS_GO_VERSION =~ ^1\.[7-9]\.[0-9]+$
branches:
    only:
        - travis
